import { StyleSheet } from "react-native";

export const stylesTrips = StyleSheet.create({
    container: {
        flex: 1,
    },
    headerContainer: {
        paddingHorizontal: 24,
        paddingTop: 60,
        marginBottom: 20,
    },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    header: {
        fontSize: 28,
        fontWeight: 'bold',
    },
    summaryGrid: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 20,
        gap: 12,
        borderWidth: 1,
        borderColor: '#eee',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    summaryCard: {
        flex: 1,
        alignItems: 'center',
    },
    summaryLabel: {
        fontSize: 10,
        color: '#888',
        fontWeight: '700',
        marginBottom: 4,
    },
    summaryValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#007AFF',
    },
    filterContainer: {
        flexDirection: 'row',
        backgroundColor: '#f0f0f0',
        borderRadius: 12,
        padding: 4,
        marginBottom: 20,
    },
    filterButton: {
        flex: 1,
        paddingVertical: 8,
        alignItems: 'center',
        borderRadius: 10,
    },
    filterButtonActive: {
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    filterButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#888',
    },
    filterButtonTextActive: {
        color: '#007AFF',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 12,
    },
    sectionHeader: {
        fontSize: 13,
        fontWeight: '700',
        color: '#888',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    sectionTotals: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    miniDot: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: '#ccc',
    },
    sectionTotalText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#888',
    },
    list: {
        paddingBottom: 40,
    },
    itemCard: {
        marginHorizontal: 24,
        padding: 16,
        borderRadius: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 8,
        elevation: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    timeGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    dateText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#333',
    },
    statusBadge: {
        backgroundColor: '#e7f5ea',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    statusText: {
        fontSize: 10,
        color: '#28a745',
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    metricsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingBottom: 12,
    },
    metric: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    metricIcon: {
        opacity: 0.8,
    },
    metricLabel: {
        fontSize: 10,
        color: '#888',
        marginBottom: 2,
    },
    metricValue: {
        fontSize: 14,
        fontWeight: '700',
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        borderTopWidth: 1,
        borderTopColor: '#f8f8f8',
        paddingTop: 8,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 80,
        paddingHorizontal: 40,
        gap: 16,
    },
    emptyText: {
        textAlign: 'center',
        fontSize: 18,
        fontWeight: '600',
    },
    emptySubText: {
        textAlign: 'center',
        fontSize: 14,
        color: '#888',
        lineHeight: 20,
    }
});