import { StyleSheet } from "react-native";

export const stylesDashboard = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: 60,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        marginBottom: 24,
    },
    greeting: {
        fontSize: 16,
        color: '#8e8e93',
        fontWeight: '500',
    },
    userName: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    syncButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        gap: 6,
    },
    syncText: {
        fontSize: 12,
        fontWeight: 'bold',
    },
    statusCard: {
        marginHorizontal: 24,
        padding: 20,
        borderRadius: 24,
        marginBottom: 24,
    },
    statusInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 8,
    },
    indicator: {
        width: 12,
        height: 12,
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    pulse: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(33, 150, 243, 0.3)',
        position: 'absolute',
    },
    statusTitle: {
        fontSize: 13,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    statusDescription: {
        fontSize: 14,
        color: '#616161',
        lineHeight: 20,
    },
    metricsGrid: {
        flexDirection: 'row',
        paddingHorizontal: 24,
        gap: 16,
        marginBottom: 16,
    },
    metricBox: {
        flex: 1,
        padding: 20,
        borderRadius: 20,
        borderWidth: 1,
        alignItems: 'flex-start',
    },
    metricValue: {
        fontSize: 22,
        fontWeight: 'bold',
        marginTop: 12,
    },
    metricLabel: {
        fontSize: 12,
        color: '#8e8e93',
        marginTop: 4,
        fontWeight: '500',
    },
    gpsHealth: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        marginTop: 8,
        marginBottom: 30,
    },
    gpsText: {
        fontSize: 12,
        color: '#8e8e93',
    },
    actionContainer: {
        padding: 24,
        paddingBottom: 40,
    },
    routeActionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    routeActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        marginHorizontal: 4,
        borderRadius: 20,
        gap: 8,
        elevation: 4,
    },
    routeActionLabel: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    mainButton: {
        flexDirection: 'row',
        height: 70,
        borderRadius: 35,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    mainButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
});
