import { StyleSheet } from "react-native";

export const stylesDashboard = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    marginBottom: 10,
  },
  greeting: {
    fontSize: 16,
    color: "#8e8e93",
    fontWeight: "500",
  },
  userName: {
    fontSize: 24,
    fontWeight: "bold",
  },
  syncButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    gap: 6,
  },
  syncText: {
    fontSize: 12,
    fontWeight: "bold",
  },
  statusCard: {
    marginHorizontal: 24,
    padding: 20,
    borderRadius: 24,
    marginBottom: 24,
  },
  statusInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  indicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  pulse: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(33, 150, 243, 0.3)",
    position: "absolute",
  },
  statusTitle: {
    fontSize: 13,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  statusDescription: {
    fontSize: 14,
    color: "#616161",
    lineHeight: 20,
  },
  metricsGrid: {
    flexDirection: "row",
    paddingHorizontal: 24,
    gap: 16,
    marginBottom: 16,
  },
  metricBox: {
    flex: 1,
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: "flex-start",
  },
  metricValue: {
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 12,
  },
  metricLabel: {
    fontSize: 12,
    color: "#8e8e93",
    marginTop: 4,
    fontWeight: "500",
  },
  gpsHealth: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 8,
    marginBottom: 30,
  },
  gpsText: {
    fontSize: 12,
    color: "#8e8e93",
  },
  actionContainer: {
    padding: 24,
    paddingBottom: 40,
  },
  routeActionsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  routeActionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    marginHorizontal: 4,
    borderRadius: 20,
    gap: 8,
    elevation: 4,
  },
  routeActionLabel: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  mainButton: {
    flexDirection: "row",
    height: 70,
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  mainButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  floatingBanner: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 6,
  },
  floatingTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  floatingTime: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  floatingActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    marginLeft: 12,
    padding: 6,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 20,
  },
  card: {
    margin: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  cardSubtitle: {
    fontSize: 14,
    marginTop: 8,
    lineHeight: 20,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  label: {
    fontSize: 15,
  },
  value: {
    fontSize: 15,
    fontWeight: '600',
  },
  odometerContainer: {
    marginTop: 12,
    padding: 12,
    borderRadius: 8,
  },
  alertText: {
    fontSize: 14,
    fontWeight: '600',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  input: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginRight: 8,
  },
  saveButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  startButton: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  startButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
